runtime: nodejs20

service: default
env: standard

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /game_page.html
  static_files: game_page.html
  upload: game_page.html

- url: /menu.html
  static_files: menu.html
  upload: menu.html

- url: /css/game.css
  static_files: game.css
  upload: css/game.css

- url: /css/index.css
  static_files: index.css
  upload: css/index.css

- url: /css/menu.css
  static_files: menu.css
  upload: css/menu.css

- url: /js/game.js
  static_files: game.js
  upload: js/game.js

- url: /js/index.js
  static_files: index.js
  upload: js/index.js

- url: /js/menu.js
  static_files: menu.js
  upload: js/menu.js

- url: /menu_page/achievements.html
  static_files: achievements.html
  upload: menu_page/achievements.html

- url: /menu_page/character.html
  static_files: character.html
  upload: menu_page/character.html

- url: menu_page/high_scores.html
  static_files: high_scores.html
  upload: menu_page/high_scores.html

- url: /menu_page/im_ready.html
  static_files: im_ready.html
  upload: menu_page/im_ready.html

- url: /menu_page/settings.html
  static_files: settings.html
  upload: menu_page/settings.html