runtime: nodejs20

service: default
env: standard

handlers:
# Serve the main pages
- url: /
  static_files: index.html
  upload: index.html

- url: /game_page.html
  static_files: game_page.html
  upload: game_page.html

- url: /menu.html
  static_files: menu.html
  upload: menu.html

# Serve the CSS files
- url: /css
  static_dir: css

# Serve the JavaScript files
- url: /js
  static_dir: js

# Serve the menu page HTML files
- url: /menu_page
  static_dir: menu_page

# Serve image files if they exist in an "Images" directory
- url: /images
  static_dir: Images